# -*- coding: utf-8 -*-
"""크롤링.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_PMddR6fPdwzItpIXSY7uhbw7erGhvdJ
"""

import pandas as pd
import numpy as np

import folium
from folium.plugins import MiniMap
import requests
from tqdm import tqdm

import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

hotel = pd.read_csv('/content/drive/MyDrive/부산 관광 아이디어 공모전/모델링) 세부분석 /기장읍/카카오/기장읍_호텔(공공데이터+야놀자)위경도_최종.csv',encoding='cp949')
hotel

# 스터디 카페
study_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'공간대여',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()#['meta']['total_count']
    study_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "전문대행 > 공간대여 > 스터디카페,스터디룸" in s]))
    #study_num.append(total)

study_num

# 공유 오피스
office_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'공유오피스',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']
    #office_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "전문대행 > 공간대여 > 스터디카페,스터디룸" in s]))

    office_num.append(total)

office_num

#관광지
관광지_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'관광지',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 10000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()
    관광지_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "여행 > 관광,명소" in s]))
    #관광지_num.append(total)

관광지_num

### 관광지
관광지_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'관광지',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 10000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()
    관광지_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "여행 > 관광,명소" in s]))
    #관광지_num.append(total)

관광지_num

"""편의시설"""

### 약국
약국_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'약국',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()
    약국_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "의료,건강 > 약국" in s]))

약국_num

### 병원
병원_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'병원',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']
    #병원_num.append([s for s in [i['category_name'] for i in total['documents']] if "노인,요양병원" not in s])
    병원_num.append(total)


병원_num

요양병원_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'요양병원',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']
    요양병원_num.append(total)

요양병원_num

병원_num = [ai - bi for ai, bi in zip(병원_num, 요양병원_num)]
병원_num

### 헬스장
헬스장_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'헬스장 ',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()
    #헬스장_num.append(total)
    헬스장_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "스포츠시설 > 헬스클럽" in s]))

헬스장_num

### 골프연습장
골프연습장_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'골프연습장 ',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()
    #골프연습장_num.append(total)['meta']['total_count']
    골프연습장_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "골프 > 골프연습장" in s]))

골프연습장_num

### 수영장
수영장_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'수영장 ',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()#['meta']['total_count']
    #수영장_num.append(total)
    수영장_num.append(len([s for s in [i['category_name'] for i in total['documents']] if  "스포츠,레저 > 수영,수상 > 수영장" in s]))

수영장_num

### 편의점
편의점_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'편의점 ',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()#['meta']['total_count']
    #편의점_num.append(total)
    편의점_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "가정,생활 > 편의점" in s]))

편의점_num

### 대형마트
대형마트_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'대형마트 ',
              'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()#['meta']['total_count']
    #대형마트_num.append(total)
    대형마트_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "가정,생활 > 대형마트" in s]))

대형마트_num

### 은행 & ATM
생활시설 =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'은행',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()
    #은행_num.append(total)
    생활시설.append(len([s for s in [i['category_name'] for i in total['documents']] if "금융,보험 > 금융서비스 > 은행" in s]))

생활시설

### 카페
카페_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'커피전문점',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']
    카페_num.append(total)
    #카페_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "식점 > 카페" in s]))

카페_num

### 음식점
음식점_num =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'음식점',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()#['meta']['total_count']
    #음식점_num.append(total)
    음식점_num.append(len([s for s in [i['category_group_name'] for i in total['documents']] if "음식점" in s]))

음식점_num

### pc방
pc_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'pc방',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK eeabe813dcb23aae644c1acaa18280fd"}
    total = requests.get(url, params=params, headers=headers).json() # ['meta']['total_count']
    pc_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "가정,생활 > 여가시설 > 게임방,PC방" in s]))
pc_num

### 공원
park_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'공원',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK eeabe813dcb23aae644c1acaa18280fd"}
    total = requests.get(url, params=params, headers=headers).json() # ['meta']['total_count']
    park_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "여행 > 공원" in s]))
park_num

### 영화관
movie_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'영화관',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK eeabe813dcb23aae644c1acaa18280fd"}
    total = requests.get(url, params=params, headers=headers).json() # ['meta']['total_count']
    movie_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "문화,예술 > 영화,영상 > 영화관" in s]))
movie_num

## 도서관
library_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'도서관',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json() # ['meta']['total_count']
    library_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "교육,학문 > 학습시설 > 도서관" in s]))
library_num

### 노래방
music_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'노래방',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK eeabe813dcb23aae644c1acaa18280fd"}
    total = requests.get(url, params=params, headers=headers).json() # ['meta']['total_count']
    music_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "가정,생활 > 여가시설 > 노래방" in s]))
music_num

"""데이터프레임 만들기 (음식점, 카페, 관광지 미포함 --> 이야기 필요)"""

의료시설 = [ai + bi for ai, bi in zip(병원_num, 약국_num)]
운동시설 = [ai + bi + ci for ai, bi, ci in zip(헬스장_num, 골프연습장_num, 수영장_num)]
구매시설 = [ai + bi for ai, bi in zip(편의점_num, 대형마트_num)]
오락시설 = [ai + bi for ai, bi in zip(music_num, pc_num)]
휴식시설 = [ai + bi + ci for ai, bi, ci in zip(park_num, movie_num, library_num)]

data = pd.concat([hotel, pd.DataFrame(list(zip(의료시설, 운동시설, 구매시설,구매시설, 휴식시설)),
                                           columns = ['의료시설', '운동시설', '구매시설', '오락시설', '휴식시설'])], axis=1)
data

data.to_csv('최종호텔선정을 위한 변수(음식점, 카페, 관광지 X).csv',index=False, encoding='UTF8')

data_합친거 = pd.read_csv('/content/drive/MyDrive/부산 관광 아이디어 공모전/모델링) 세부분석 /기장읍/카카오/최종호텔선정을 위한 변수(음식점, 카페, 관광지 X).csv')
data_합친거

### 관광지
관광지_num =[]
for i in tqdm(range(0,len(data_합친거))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'관광지',
              'x': data_합친거["경도"][i],
              'y':data_합친거['위도'][i],
              'radius': 10000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']
    #관광지_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "여행 > 관광,명소" in s]))
    관광지_num.append(total)

관광지_num

### 음식점
음식점_num =[]
for i in tqdm(range(0,len(data_합친거))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'음식점',
                'x': data_합친거["경도"][i],
              'y':data_합친거['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']
    음식점_num.append(total)
    #음식점_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "음식점" in s]))

음식점_num

### 카페
카페_num =[]
for i in tqdm(range(0,len(data_합친거))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'커피전문점',
                'x': data_합친거["경도"][i],
              'y':data_합친거['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']
    카페_num.append(total)
    #카페_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "식점 > 카페" in s]))

카페_num

### 은행 & ATM
생활시설 =[]
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'은행',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()
    #은행_num.append(total)
    생활시설.append(len([s for s in [i['category_name'] for i in total['documents']] if "금융,보험 > 금융서비스 > 은행" in s]))

생활시설

# 스터디 카페
study_num = []
for i in tqdm(range(0,len(hotel))):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query':'공간대여',
                'x': hotel["경도"][i],
              'y':hotel['위도'][i],
              'radius': 1000}
    headers = {"Authorization": "KakaoAK 1a7195a14d786682aecda5217e9396d1"}
    total = requests.get(url, params=params, headers=headers).json()#['meta']['total_count']
    study_num.append(len([s for s in [i['category_name'] for i in total['documents']] if "전문대행 > 공간대여 > 스터디카페,스터디룸" in s]))
    #study_num.append(total)

study_num

식음시설 = [ai + bi for ai, bi in zip(음식점_num, 카페_num)]

data_fin = pd.concat([data_합친거, pd.DataFrame(list(zip(식음시설, 관광지_num,생활시설,study_num)),
                                           columns = ['식음시설', '관광지','생활시설','업무시설'])], axis=1)
data_fin

data_fin.columns

data_fin = data_fin[['숙박업소명', '영업소 주소(도로명)','위도', '경도', '의료시설', '운동시설', '구매시설', '오락시설', '휴식시설', '식음시설','관광지', '생활시설','업무시설']]
data_fin

data_fin[['의료시설', '운동시설', '구매시설', '오락시설', '휴식시설','생활시설']].sum(axis=1)

data_fin['편의시설'] = data_fin[['의료시설', '운동시설', '구매시설', '오락시설', '휴식시설','생활시설']].sum(axis=1)
data_fin = data_fin[['숙박업소명', '영업소 주소(도로명)','위도', '경도', '편의시설', '식음시설','관광지','업무시설']]
data_fin

data_fin= data_fin.rename(columns = {'영업소 주소(도로명)	':'주소'}, inplace = True)

data_fin.columns  =  ['숙박업소명', '주소','위도', '경도', '편의시설', '식음시설','관광지','업무시설']
data_fin

data_fin.to_csv('찐최종.csv',index=False, encoding='UTF8')